baseURL = "https://dawnstar.berlin/"
languageCode = "en-gb"
title = "Dawnstar"
theme = "dawnstar2018"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  description = "Notes about music and life"
