baseURL = "https://dawnstar.berlin/"
languageCode = "en-gb"
title = "Dawnstar"
theme = "dawnstar2018"
[taxonomies]
  tag = "tags"
[permalinks]
  posts = "/:year/:month/:day/:title/"
[params]
  description = "Notes about music and life"
