baseURL = "https://dawnstar.blog/"
locale = "en-gb"
title = "Dawnstar"
theme = "dawnstar2018"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.x]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
  description = "Notes about music and life"

[build]
  writeStats = true
